# !! It should be better to split this config file for bounded context. Skipped for simplicity. !!
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            user_id: App\User\Infrastructure\DB\Doctrine\Type\UserIDType
            sf_user_role_id: App\User\Infrastructure\DB\Doctrine\Type\SymfonyUserRoleIDType
            participant_id: App\League\Infrastructure\DB\Doctrine\Type\ParticipantIDType
            league_id: App\League\Infrastructure\DB\Doctrine\Type\LeagueIDType
            customer_id: App\Accounting\Infrastructure\DB\Doctrine\Type\CustomerIDType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Domain/Model'
                prefix: 'App\User\'
                alias: User
            SymfonyUser:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Infrastructure/Model/User/Symfony'
                prefix: 'App\SymfonyUser\'
                alias: SymfonyUser
            League:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/League/Domain/Model'
                prefix: 'App\League\'
                alias: Participant
            Accounting:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Accounting/Domain/Model'
                prefix: 'App\Accounting\'
                alias: Accounting
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
