# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
imports:
    - { resource: league.yaml }
    - { resource: user.yaml }

framework:
    http_client:
        scoped_clients:
            api_client:
                base_uri: '%base_uri%'

parameters:
    base_uri: 'http://172.20.0.2:8000/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\League\Application\Service\Participant\Provider\ParticipantProviderApplicationInterface:
            tags: ['app.league.participant.provider.application_provider']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/**/Model/*.php'
            - '../src/User/Application/Service/UserSuspendedHandler.php'
            - '../src/User/Application/Service/UserSuspensionRevokedHandler.php'

    App\League\Application\Service\Participant\Provider\ParticipantChainedProvider:
        arguments:
            $providers: !tagged app.league.participant.provider.application_provider

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
